### ISSUE TITLE
Not working with redirection

### ISSUE THREAD

**Issue by maisoui** [elegos/slim3AnnotationRouter#1]
Hi,

It seems your router is not compatible with redirection. According to Slim 3 documentation, I redirect the request using: 

`$res->withStatus(302)->withHeader('Location', '...');
or
return $response->withRedirect($this->router->pathFor($routeName, []));`

The result is a blank page, instead of redirecting to the correct url.
Do you have a fix ?

Best regards

**Comment by maisoui** [comment]
Apparently, it's generalized to all methods $response->with...

**Comment by maisoui** [comment]
I found the issue: In the method, Router:registerRoutes, the anonymous method must return a ResponseInterface: return $class->{$route->getClassMethod()}(...$methodArgs);

**Comment by elegos** [comment]
Helo @maisoui,

I'm really sorry for the delay, but I really didn't see the notifications. I'll revew your pulll request ASAP. Thank you :)

**Comment by elegos** [comment]
Fixed via #2
